name: Sync Design Tokens

on:
  push:
    branches:
      - main

jobs:
  sync-design-tokens:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to make a proper commit

      - name: Install Babashka
        run: |
          # Download the latest Babashka release
          curl -sLo bb.zip https://github.com/babashka/babashka/releases/latest/download/babashka-standalone-linux-amd64.zip
          # Unzip the downloaded file
          unzip bb.zip
          # Move the bb binary to a directory in PATH
          sudo mv bb /usr/local/bin/
          # Clean up
          rm bb.zip
          # Verify installation
          bb --version

      - name: Run sync_design_tokens.clj
        run: bb sync_design_tokens.clj

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected. Committing and pushing..."
            git config user.name "GitHub Action"
            git config user.email "action@github.com"
            git add .
            git commit -m "Update design tokens [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
