name: Sync Design Tokens

on:
  push:
    branches:
      - main

jobs:
  sync-design-tokens:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to make a proper commit

      - name: Install bb
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          bb: 0.7.8                    # Babashka

      - name: Run sync_design_tokens.clj
        run: bb ./scripts/sync_design_tokens.clj

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected. Committing and pushing..."
            git config user.name "GitHub Action"
            git config user.email "action@github.com"
            git add .
            git commit -m "Update design tokens [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
